/**
 * Synthetic demo data — fictional people and IT roles only; no real employees.
 * photoUrl: stock portraits from randomuser.me (common demo CDN).
 * Categories: Education, Public Speaking, University Partnership (SharePoint filter).
 */
window.LEADERBOARD_RAW_ACTIVITIES = [
  {
    displayName: "Elena Kovacs",
    role: "Senior Frontend Engineer",
    photoUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    date: "2025-01-12",
    category: "Education",
    points: 40,
    activityTitle: "[EDU] Internal workshop: design systems and accessibility",
  },
  {
    displayName: "Elena Kovacs",
    role: "Senior Frontend Engineer",
    photoUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    date: "2025-02-03",
    category: "Public Speaking",
    points: 25,
    activityTitle: "[EDU] Lightning talk: performance budgets in practice",
  },
  {
    displayName: "Elena Kovacs",
    role: "Senior Frontend Engineer",
    photoUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    date: "2025-04-18",
    category: "University Partnership",
    points: 30,
  },
  {
    displayName: "Marco Silva",
    role: "Platform Engineer",
    photoUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    date: "2025-01-20",
    category: "Education",
    points: 55,
  },
  {
    displayName: "Marco Silva",
    role: "Platform Engineer",
    photoUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    date: "2025-03-10",
    category: "Education",
    points: 20,
  },
  {
    displayName: "Marco Silva",
    role: "Platform Engineer",
    photoUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    date: "2025-03-22",
    category: "Education",
    points: 80,
  },
  {
    displayName: "Priya Sharma",
    role: "Staff Software Engineer",
    photoUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    date: "2025-02-14",
    category: "Public Speaking",
    points: 35,
  },
  {
    displayName: "Priya Sharma",
    role: "Staff Software Engineer",
    photoUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    date: "2025-04-02",
    category: "University Partnership",
    points: 15,
  },
  {
    displayName: "Priya Sharma",
    role: "Staff Software Engineer",
    photoUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    date: "2025-04-28",
    category: "Education",
    points: 22,
  },
  {
    displayName: "James O'Brien",
    role: "IT Operations Manager",
    photoUrl: "https://randomuser.me/api/portraits/men/52.jpg",
    date: "2025-01-05",
    category: "University Partnership",
    points: 60,
  },
  {
    displayName: "James O'Brien",
    role: "IT Operations Manager",
    photoUrl: "https://randomuser.me/api/portraits/men/52.jpg",
    date: "2025-02-28",
    category: "Public Speaking",
    points: 18,
  },
  {
    displayName: "Sofia Andersson",
    role: "Cloud Solution Architect",
    photoUrl: "https://randomuser.me/api/portraits/women/33.jpg",
    date: "2025-03-01",
    category: "Education",
    points: 45,
  },
  {
    displayName: "Sofia Andersson",
    role: "Cloud Solution Architect",
    photoUrl: "https://randomuser.me/api/portraits/women/33.jpg",
    date: "2025-03-15",
    category: "Education",
    points: 30,
  },
  {
    displayName: "Sofia Andersson",
    role: "Cloud Solution Architect",
    photoUrl: "https://randomuser.me/api/portraits/women/33.jpg",
    date: "2025-04-10",
    category: "Public Speaking",
    points: 28,
  },
  {
    displayName: "Daniel Ng",
    role: "Site Reliability Engineer",
    photoUrl: "https://randomuser.me/api/portraits/men/85.jpg",
    date: "2025-01-30",
    category: "Education",
    points: 24,
  },
  {
    displayName: "Daniel Ng",
    role: "Site Reliability Engineer",
    photoUrl: "https://randomuser.me/api/portraits/men/85.jpg",
    date: "2025-04-05",
    category: "University Partnership",
    points: 50,
  },
  {
    displayName: "Anna Kowalski",
    role: "Engineering Manager",
    photoUrl: "https://randomuser.me/api/portraits/women/26.jpg",
    date: "2025-02-08",
    category: "Public Speaking",
    points: 42,
  },
  {
    displayName: "Anna Kowalski",
    role: "Engineering Manager",
    photoUrl: "https://randomuser.me/api/portraits/women/26.jpg",
    date: "2025-04-12",
    category: "Education",
    points: 36,
  },
  {
    displayName: "Viktor Petrov",
    role: "Backend Developer",
    photoUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    date: "2025-01-18",
    category: "Education",
    points: 33,
  },
  {
    displayName: "Viktor Petrov",
    role: "Backend Developer",
    photoUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    date: "2025-03-30",
    category: "Education",
    points: 27,
  },
  {
    displayName: "Laura Chen",
    role: "Product Manager",
    photoUrl: "https://randomuser.me/api/portraits/women/79.jpg",
    date: "2025-02-22",
    category: "University Partnership",
    points: 20,
  },
  {
    displayName: "Laura Chen",
    role: "Product Manager",
    photoUrl: "https://randomuser.me/api/portraits/women/79.jpg",
    date: "2025-04-20",
    category: "Public Speaking",
    points: 24,
  },
  {
    displayName: "Thomas Weber",
    role: "Lead Data Engineer",
    photoUrl: "https://randomuser.me/api/portraits/men/41.jpg",
    date: "2025-03-08",
    category: "Education",
    points: 70,
  },
  {
    displayName: "Thomas Weber",
    role: "Lead Data Engineer",
    photoUrl: "https://randomuser.me/api/portraits/men/41.jpg",
    date: "2025-04-01",
    category: "Education",
    points: 15,
  },
  {
    displayName: "Yuki Tanaka",
    role: "Principal UX Designer",
    photoUrl: "https://randomuser.me/api/portraits/women/50.jpg",
    date: "2025-01-25",
    category: "Public Speaking",
    points: 38,
  },
  {
    displayName: "Yuki Tanaka",
    role: "Principal UX Designer",
    photoUrl: "https://randomuser.me/api/portraits/women/50.jpg",
    date: "2025-04-15",
    category: "University Partnership",
    points: 22,
  },
  {
    displayName: "Rachel Brooks",
    role: "QA Automation Engineer",
    photoUrl: "https://randomuser.me/api/portraits/women/17.jpg",
    date: "2025-02-11",
    category: "Education",
    points: 29,
  },
  {
    displayName: "Rachel Brooks",
    role: "QA Automation Engineer",
    photoUrl: "https://randomuser.me/api/portraits/women/17.jpg",
    date: "2025-03-25",
    category: "Public Speaking",
    points: 31,
  },
  {
    displayName: "Olivier Dupont",
    role: "Technical Program Manager",
    photoUrl: "https://randomuser.me/api/portraits/men/76.jpg",
    date: "2025-01-08",
    category: "Education",
    points: 90,
  },
  {
    displayName: "Olivier Dupont",
    role: "Technical Program Manager",
    photoUrl: "https://randomuser.me/api/portraits/men/76.jpg",
    date: "2025-02-19",
    category: "Education",
    points: 12,
  },
  {
    displayName: "Olivier Dupont",
    role: "Technical Program Manager",
    photoUrl: "https://randomuser.me/api/portraits/men/76.jpg",
    date: "2025-04-22",
    category: "University Partnership",
    points: 10,
  },
];
